# Generated by Django 3.1.5 on 2021-01-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Robot', 'ROBOT_GEAR'), ('Automatic', 'AUTOMATIC_GEAR'), ('Manual', 'MANUAL_GEAR')], default='Manual', max_length=255),
        ),
    ]
