# Generated by Django 3.1.5 on 2021-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210122_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='small_photo',
            field=models.ImageField(blank=True, upload_to='cars_photo/small'),
        ),
    ]
